table 'Dim Customers'
	lineageTag: 80914a5a-c275-4f94-a88b-de9dcc725e3d

	column 'Customer ID'
		dataType: string
		lineageTag: bd5216bb-70ae-4920-b6b8-dd63f7890936
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: c4d68fc1-b45e-4485-a146-3cd6bae9279f
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: e470a83f-c042-45dd-b9c8-410b5787476e
		dataCategory: City
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: d58c01fb-320c-4ab9-a7aa-56a9c33f52a1
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column Pincode
		dataType: int64
		formatString: 0
		lineageTag: 24b3d465-4858-44a4-bffd-5aa1575eeb09
		summarizeBy: none
		sourceColumn: Pincode

		annotation SummarizationSetBy = Automatic

	column EmailID
		dataType: string
		lineageTag: f07eb750-49fc-46d8-9884-4f20de1cb130
		summarizeBy: none
		sourceColumn: EmailID

		annotation SummarizationSetBy = Automatic

	column 'Phone Number'
		dataType: int64
		formatString: 0
		lineageTag: 1199cccc-9b42-4001-9916-d8d54da229f0
		summarizeBy: none
		sourceColumn: Phone Number

		annotation SummarizationSetBy = Automatic

	partition 'Dim Customers' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("D:\Data Analytics\Power Bi\Store Data.xlsx"), null, true),
				    #"Dim Customers_Sheet" = Source{[Item="Dim Customers",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Dim Customers_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Customer ID", type text}, {"Customer Name", type text}, {"City", type text}, {"State", type text}, {"Pincode", Int64.Type}, {"EmailID", type text}, {"Phone Number", Int64.Type}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type", "Index", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index",{"Index", "Customer ID", "Customer Name", "City", "State", "Pincode", "EmailID", "Phone Number"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"Index"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

